nx-vin-objs = nx-vip-primitive.o nx-vip.o
obj-$(CONFIG_VIDEO_NEXELL_CAPTURE)	+= nx-vin.o
obj-$(CONFIG_VIDEO_NEXELL_MIPI_CSI)	+= nx-csi.o
obj-$(CONFIG_VIDEO_NEXELL_CLIPPER)  += nx-clipper.o
obj-$(CONFIG_VIDEO_NEXELL_DECIMATOR) += nx-decimator.o
